# pvc-1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ma-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard