version: '3.8'

services:
  app:
    environment: 
        - DJANGO_SETTINGS_MODULE=mlarchive.settings.settings_docker
    build:
      context: .
      dockerfile: docker/app-dev.Dockerfile
    ports:
      - 8005:8000

    init: true

    # use when not using ENTRYPOINT
    # command: sleep infinity

    # network_mode: service:db

    depends_on:
        - db
        - es
        - rabbit

    ipc: host
    volumes:
        - app-data:/data
        - app-assets:/assets

  es:
    image: "elasticsearch:7.17.4"
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
    volumes:
        - es-data:/usr/share/elasticsearch/data
        
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: mailarch
      POSTGRES_USER: django
      POSTGRES_PASSWORD: franticmarble
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - postgresdb-data:/var/lib/postgresql/data

  rabbit:
    image: rabbitmq:3.10
    restart: always

volumes:
    app-assets:
    app-data:
    postgresdb-data:
    es-data:
