version: '3.8'

services:
  app:
    environment: 
        - DJANGO_SETTINGS_MODULE=mlarchive.settings.settings_docker
    build:
      context: .
      dockerfile: docker/app-dev.Dockerfile
    ports:
      - target: 8000 published: 8005

    init: true

    command: sleep infinity

    # network_mode: service:db

    depends_on:
        - db
        - es
        - rabbit

    ipc: host

  es:
    image: "elasticsearch:7.17.4"
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_DB: mailarch
      POSTGRES_USER: django
      POSTGRES_PASSWORD: franticmarble
      POSTGRES_HOST_AUTH_METHOD: trust

  rabbit:
    image: rabbitmq:3.10
    restart: always
