apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailarchive.fullname" . }}
  labels:
    {{- include "mailarchive.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mailarchive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mailarchive.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mailarchive.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-chmod-data
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["mkdir -p /data/archive; mkdir -p /data/log/mail-archive;"]
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              # Wait for the database to be ready
              while ! nc -z -w 1 mailarchive-postgresql 5432; do
                echo "Waiting for database to be ready..."
                sleep 1
              done
        - name: wait-for-elasticsearch
          image: busybox
          command:
            - sh
            - -c
            - |
              # Wait for the index to be ready
              while ! nc -z -w 1 elasticsearch-master 9200; do
                echo "Waiting for elasticsearch index to be ready..."
                sleep 1
              done
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "mailarchive.db.env" . | nindent 12 }}
            - name: CONTAINER_ROLE
              value: {{ .Values.env.CONTAINER_ROLE | quote }}
            - name: ELASTICSEARCH_HOST
              value: {{ .Values.env.ELASTICSEARCH_HOST | quote }}
            - name: IMPORT_MESSAGE_APIKEY
              value: {{ .Values.env.IMPORT_MESSAGE_APIKEY | quote }}
            - name: CELERY_BROKER_URL
              value: {{ .Values.env.CELERY_BROKER_URL | quote }}
            - name: MEMCACHED_SERVICE_HOST
              value: {{ .Values.env.MEMCACHED_SERVICE_HOST | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.env.DJANGO_SETTINGS_MODULE | quote }}
            - name: SCOUT_NAME
              value: {{ .Values.env.SCOUT_NAME | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
