# pvc-1.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mailarchive-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: mailarchive-data-volume