apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailarchive
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mailarchive
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailarchive
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox
          command: ['sh', '-c', 'until nc -z ml-elasticsearch 9200; do echo "Waiting for Elasticsearch..."; sleep 5; done; echo "Elasticsearch is up!"']
          securityContext:
            runAsUser: 1000  # Non-root user ID
            runAsGroup: 1000  # Non-root group ID
            allowPrivilegeEscalation: false
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z ml-rabbitmq 5672; do echo "Waiting for Rabbitmq..."; sleep 5; done; echo "Rabbitmq is up!"']
          securityContext:
            runAsUser: 1000  # Non-root user ID
            runAsGroup: 1000  # Non-root group ID
            allowPrivilegeEscalation: false
        - name: wait-for-memcached
          image: busybox
          command: ['sh', '-c', 'until nc -z ml-memcached 11211; do echo "Waiting for Memcached..."; sleep 5; done; echo "Memcached is up!"']
          securityContext:
            runAsUser: 1000  # Non-root user ID
            runAsGroup: 1000  # Non-root group ID
            allowPrivilegeEscalation: false
      containers:
        # -----------------------------------------------------
        # Mail Archive Container
        # -----------------------------------------------------
        - name: mailarchive
          image: "ghcr.io/ietf-tools/mailarchive:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: ml-vol
              mountPath: /mnt/mailarchive
            - name: ml-tmp
              mountPath: /tmp
          env:
            - name: "CONTAINER_ROLE"
              value: "mailarchive"
            # ensures the pod gets recreated on every deploy:
            - name: "DEPLOY_UID"
              value: "$DEPLOY_UID"
          envFrom:
            - configMapRef:
                name: django-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
        # -----------------------------------------------------
        # Nginx Container
        # -----------------------------------------------------
        - name: nginx
          image: "ghcr.io/nginxinc/nginx-unprivileged:1.27"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /health/nginx
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: nginx-tmp
              mountPath: /tmp
            - name: ml-cfg
              mountPath: /etc/nginx/conf.d/00logging.conf
              subPath: nginx-logging.conf
            - name: ml-cfg
              mountPath: /etc/nginx/conf.d/mailarchive.conf
              subPath: nginx-mailarchive.conf
        # -----------------------------------------------------
        # ScoutAPM Container
        # -----------------------------------------------------
        - name: scoutapm
          image: "scoutapp/scoutapm:version-1.4.0"
          imagePullPolicy: IfNotPresent
          # Replace command with one that will shut down on a TERM signal
          # The ./core-agent start command line is from the scoutapm docker image
          command:
            - "sh"
            - "-c"
            - >-
              trap './core-agent shutdown --tcp 0.0.0.0:6590' TERM;
              ./core-agent start --daemonize false --log-level warn --tcp 0.0.0.0:6590 &
              wait $!
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "./core-agent probe --tcp 0.0.0.0:6590 | grep -q 'Agent found'"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534 # "nobody" user by default
            runAsGroup: 65534  # "nogroup" group by default
      volumes:
        # To be overriden with the actual shared volume
        - name: ml-vol
        - name: ml-tmp
          emptyDir:
            sizeLimit: "2Gi"
        - name: ml-cfg
          configMap:
            name: files-cfgmap
        - name: nginx-tmp
          emptyDir:
            sizeLimit: "500Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mailarchive
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mailarchive
