apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailarchive
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mailarchive
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailarchive
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        # -----------------------------------------------------
        # ScoutAPM Container
        # -----------------------------------------------------
        - name: scoutapm
          image: "scoutapp/scoutapm:version-1.4.0"
          imagePullPolicy: IfNotPresent
          # Replace command with one that will shut down on a TERM signal
          # The ./core-agent start command line is from the scoutapm docker image
          command:
            - "sh"
            - "-c"
            - >-
              trap './core-agent shutdown --tcp 0.0.0.0:6590' TERM;
              ./core-agent start --daemonize false --log-level notice --tcp 0.0.0.0:6590 &
              wait $!
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "./core-agent probe --tcp 0.0.0.0:6590 | grep -q 'Agent found'"
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534 # "nobody" user by default
            runAsGroup: 65534  # "nogroup" group by default
        # -----------------------------------------------------
        # Mail Archive Container
        # -----------------------------------------------------
        - name: mailarchive
          image: "ghcr.io/ietf-tools/mailarchive:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: ml-vol
              mountPath: /mnt/mailarchive
            - name: dt-vol
              mountPath: /mnt/datatracker
            - name: ml-tmp
              mountPath: /tmp
          env:
            - name: "CONTAINER_ROLE"
              value: "mailarchive"
          envFrom:
            - configMapRef:
                name: django-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        # To be overriden with the actual shared volume
        - name: ml-vol
        - name: dt-vol
        - name: ml-tmp
          emptyDir:
            sizeLimit: "2Gi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mailarchive
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mailarchive
