apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      initContainers:
        - name: setup-erlang-cookie
          image: busybox
          command: ['sh', '-c', 'echo "lorem-ipsum-dolor-sit-amet" > /var/lib/rabbitmq/.erlang.cookie; chmod 0600 /var/lib/rabbitmq/.erlang.cookie;']
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
      containers:
        # -----------------------------------------------------
        # RabbitMQ Container
        # -----------------------------------------------------
        - image: "rabbitmq:3"
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-tmp
              mountPath: /tmp
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: mailarch
            - name: RABBITMQ_DEFAULT_PASS
              value: bugsbunny
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            periodSeconds: 30
            timeoutSeconds: 5
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 60
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: rabbitmq-tmp
          emptyDir:
            sizeLimit: "50Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
      # storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  clusterIP: None  # headless service
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: amqp
  selector:
    app: rabbitmq
