name: Reusable Tests Workflow

on:
  workflow_call:
    inputs:
      ignoreLowerCoverage:
        description: 'Ignore Lower Coverage'
        default: false
        required: true
        type: boolean
      skipSelenium:
        description: 'Skip Selenium Tests'
        default: false
        required: false
        type: boolean
      targetBaseVersion:
        description: 'Target Base Image Version'
        default: latest
        required: false
        type: string

jobs:
  tests-python:
    name: Python Tests
    runs-on: ubuntu-latest
    container: ghcr.io/ietf-tools/mailarchive-app-base:${{ inputs.targetBaseVersion }}
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare for tests
      run: |
        chmod +x ./dev/tests/prepare.sh
        sh ./dev/tests/prepare.sh
        
    - name: Run all tests
      shell: bash
      run: |
        echo "Running tests..."
        cd backend/mlarchive
        pytest tests -v
